name: Build and Push user-service Docker Image

on:
  push:
    paths:
      - 'user-service/**'  # Ejecutar el workflow solo si hay cambios en el directorio 'user-service'
    branches:
      - develop  # Ejecutar el workflow cuando haya cambios en la rama 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Usar un runner de Ubuntu para ejecutar el workflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Obtener el código fuente del repositorio

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Configurar Docker Buildx para la construcción de imágenes

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Iniciar sesión en Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usar el secret DOCKER_USERNAME
        password: ${{ secrets.DOCKER_PASSWORD }}  # Usar el secret DOCKER_PASSWORD

    - name: Build and push Docker image
      uses: docker/build-push-action@v5  # Usar la acción Buildx para construir y subir la imagen
      with:
        context: ./user-service  # El contexto es el directorio del microservicio 'user-service'
        file: ./user-service/Dockerfile  # Especifica el Dockerfile dentro del servicio
        push: true  # Esto asegura que la imagen se suba al Docker Hub
        tags: jacito/user-service:latest  # La etiqueta de la imagen (puedes cambiarla si lo prefieres)
